apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    name: webapp-pod
    app: webapp
spec:
  containers:
    - name: webapp
      image: nhan2102/lms:aws
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123"
        - name: MYSQL_PASSWORD
          value: "admin"
        - name: MYSQL_DATABASE
          value: "mariadb"
      ports:
        - containerPort: 8000
        - containerPort: 9000
      imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    name: webapp-service
    app: webapp
spec:
  type: LoadBalancer
  selector:
    name: webapp-pod
    app: webapp
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: http-alt
      port: 9000
      targetPort: 9000